import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script'
import ConfigurationContextProvider from '@/components/configuration-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const rjsSrc = 'https://js.recurly.dev:8020/build/recurly.js';
  // const rjsSrc = 'https://js.recurly.com/v4/recurly.js';
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://js.recurly.com/v4/recurly.css" />
      </head>

      <body className={inter.className}>
        <ConfigurationContextProvider>
          {children}
        </ConfigurationContextProvider>
      </body>
    </html>
  )
}
